services:
  portfolio:
    image: nginx:latest
    container_name: portfolio
    ports:
      - "8081:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped